<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Umbraco.Community.SmartRedirectSuggester</Product>
    <PackageId>Umbraco.Community.SmartRedirectSuggester</PackageId>
    <Title>Smart Redirect Suggester </Title>
    <Description>...</Description>
    <PackageTags>umbraco;umbraco-marketplace</PackageTags>
    <Authors>Søren Kottal</Authors>
    <Copyright>$([System.DateTime]::UtcNow.ToString(`yyyy`)) © Søren Kottal</Copyright>
    <PackageProjectUrl>https://github.com/skttl/umbraco-smartredirectsuggester</PackageProjectUrl>
    <RepositoryUrl>https://github.com/skttl/umbraco-smartredirectsuggester</RepositoryUrl>
    <PackageReadmeFile>README_nuget.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon></PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Web.Website" />
    <PackageReference Include="Umbraco.Cms.Web.Common" />
    <PackageReference Include="Umbraco.Cms.Api.Common" />
    <PackageReference Include="Umbraco.Cms.Api.Management" />
    <PackageReference Include="Umbraco.Cms.Search.Core" />
  </ItemGroup>

  <ItemGroup>
    <!-- Dont include the client folder as part of packaging nuget build -->
    <Content Remove="Client\**" />
    <Compile Remove="Controllers\ImportFirehoseNewsController.cs" />
    <Compile Remove="Models\FirehoseNewsImportModels.cs" />
    <Compile Remove="Services\IFirehoseNewsImportService.cs" />
    <Compile Remove="Services\FirehoseNewsImportService.cs" />

    <!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
    <None Include="Client\public\umbraco-package.json" Pack="false" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\docs\README_nuget.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
